import { MRT_Localization } from 'material-react-table';

const localization: Partial<MRT_Localization> | undefined = {
  actions: 'Ações',
  showHideColumns: 'Mostrar/Ocultar Colunas',
  showHideFilters: 'Mostrar/Ocultar Filtros',
  search: 'Pesquisar',
  noRecordsToDisplay: 'Nenhum registro para exibir',
  rowsPerPage: 'Linhas por página',
  of: 'de',
  and: 'e',
  cancel: 'Cancelar',
  clearSearch: 'Limpar Pesquisa',
  clearSort: 'Limpar Ordenação',
  edit: 'Editar',
  filterByColumn: 'Filtrar por coluna',
  goToFirstPage: 'Ir para a primeira página',
  goToLastPage: 'Ir para a última página',
  goToNextPage: 'Ir para a próxima página',
  goToPreviousPage: 'Ir para a página anterior',
  sortByColumnAsc: 'Ordenar por coluna ascendente',
  sortByColumnDesc: 'Ordenar por coluna descendente',
  sortedByColumnAsc: 'Ordenado por coluna ascendente',
  sortedByColumnDesc: 'Ordenado por coluna descendente',
  toggleDensity: 'Alternar densidade',
  toggleFullScreen: 'Alternar tela cheia',
  toggleSelectAll: 'Alternar selecionar tudo',
  toggleSelectRow: 'Alternar selecionar linha',
  toggleVisibility: 'Alternar visibilidade',
  changeFilterMode: 'Alterar modo de filtro',
  changeSearchMode: 'Alterar modo de pesquisa',
  clearSelection: 'Limpar seleção',
  collapseAll: 'Recolher tudo',
  clearFilter: 'Limpar filtro',
  collapse: 'Recolher',
  expand: 'Expandir',
  expandAll: 'Expandir tudo',
  hideAll: 'Ocultar tudo',
  showAll: 'Mostrar tudo',
  resetColumnSize: 'Redefinir tamanho da coluna',
  // Adicione outras traduções conforme necessário
};

export default localization;
